[package]
name = "hydra"
version = "0.7.0"
edition = "2021"
authors = ["Thomas J. Mathis <tmathis720@gmail.com>"]
description = "Hydra CFD data management and solver framework"
license = "MIT"
repository = "https://github.com/tmathis720/HYDRA"
readme = "README.md"
exclude = ["/ci/*", "/scripts/*", "/.github/*"]

[lib]
name = "hydra"
path = "src/lib.rs"

[dependencies]
<<<<<<< HEAD
rustc-hash = "2.0.0"
faer = { version = "0.21", features = ["rayon"] }
rayon = "1.5"
=======
rustc-hash = "2.1.0"
faer = { version = "0.19", features = ["rayon"] }
rayon = "1.10"
>>>>>>> 6e12a9f265287043d52e378686f96f25015b3cae
crossbeam = "0.8.4"
dashmap = "6.1"
approx = "0.5"
lazy_static = "1.5"

[dev-dependencies]
criterion = "0.4"
rand = "0.8"