[package]
name = "hydra"
version = "0.3.0"
edition = "2021"

[lib]
name = "hydra"
path = "src/lib.rs"

[dependencies]
rustc-hash = "2.0.0"
rayon = "1.5"
faer = "0.17"
faer-lu = "0.17"
faer-core = "0.17"

[dev-dependencies]
criterion = "0.4"
rand = "0.8"