[package]
name = "hydra"
version = "0.3.0"
edition = "2021"

[lib]
name = "hydra"
path = "src/lib.rs"

[dependencies]
rustc-hash = "2.0.0"
faer = { version = "0.19", features = ["rayon"] }
rayon = "1.5"
crossbeam = "0.8.4"
pest = "2.7"
pest_derive = "2.7"

[dev-dependencies]
criterion = "0.4"
rand = "0.8"